### ISSUE TITLE
Authorizer implementation

### ISSUE THREAD

**Issue by alexjurkiewicz** [terraform-aws-modules/terraform-aws-apigateway-v2#20]
Hi Anton, I like this module a lot! Do you have plans to add authorizer support to it? It's something I'm possibly interested in working on. Do you have ideas about how the implementation should look?

**Comment by antonbabenko** [comment]
Hi Alex! Recently there was #17 about authorization on routes.

If you are thinking about the creation of `aws_apigatewayv2_authorizer` resources by this module, then I don't have immediate plans to add those because I don't have a need for them myself.

From the implementation point of view, `aws_apigatewayv2_authorizer` resources should be similar to the relation between `var.integrations` and `aws_apigatewayv2_route` resources.

I will be glad to review the implementation if anyone wants to work on it.

**Comment by bobbydeveaux** [comment]
I've created a PR here: 
https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/pull/64 

@antonbabenko  do you mind giving a review please? :)
